version: '3'

services:
  fakermap:
    container_name: fakermap
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: faker
      SLEEP_TIME: 30

networks:
  default:
    external:
      name: kafka-network
